name: cardano_dart_types
description: Part of Cardano Flutter SDK containing the data models.
version: 2.9.4
homepage: https://github.com/vespr-wallet/cardano_dart_types
repository: https://github.com/vespr-wallet/cardano_dart_types
issue_tracker: https://github.com/vespr-wallet/cardano_dart_types/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bip32_ed25519: ^0.6.0 # for generating/deriving keys
  cbor:
    ^6.3.3 # to encode/decode cbor transactions
    #  git:
    #    url: https://github.com/vespr-wallet/cbor.git
    #    ref: 2d46b32519e9ed5a07e8e2528e00fa0a9e0770e7
  # pinenacl: ^0.6.0 # for cryptographic signatures and hashing
  # bip39: ^1.0.6 # to generate mnemonics and convert them to entropy
  # bip39:
  #   git:
  #     url: https://github.com/vespr-wallet/bip39.git
  #     ref: develop # fix/modal_bottom_sheet
  # typed_data: ^1.3.2 # For Uint8List and other Buffers
  collection: ^1.18.0 # to use collection extension methods
  fast_base58: ^0.2.1 # to/from base58 string conversion (used for byron addresses)
  freezed_annotation: ^3.0.0 # to generate data classes
  hex: ^0.2.0 # to/from hex string conversion
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner:
  freezed: ^3.0.6
  json_serializable: ^6.9.0
  lints: ^6.0.0
  test: ^1.25.7
  # dependency_validator: ^4.0.0
  #  mockito: ^5.4.2
  # dependency_overrides:
  # bip32_ed25519:
  #   path: ../bip32-ed25519-dart
